### ISSUE TITLE
use regular expressions to resolve literals; URIs, CURIEs

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/yaml-ld#83]
As a data architect
I want YAML plain values to be recognized by regular expression
So that I don't have to explicitly tag them

- The YAML spec https://yaml.org/spec/1.2.2/#332-resolved-tags says
"Application specific tag resolution rules should be restricted to resolving the “?” non-specific tag, most commonly to resolving plain scalars. These may be matched against a set of regular expressions to provide automatic resolution of integers, floats, timestamps and similar types."
- The default "JSON schema" https://yaml.org/spec/1.2.2/#102-json-schema includes regexes for matching integers and floats
- The extended "Core schema" https://yaml.org/spec/1.2.2/#103-core-schema includes regexes for matching integers, floats, NaNs, null, booleans
- The https://yaml.org/type collection lists further interesting cases:
  - https://yaml.org/type/timestamp.html for timestamps (such examples used to be in the spec, but are being deprecated)
  - https://yaml.org/type/value.html for extensibility of strings with extra attributes
- We could define regexes for matching URNs and IRIs instead of tagging them explicitly #79

Examples (Tagging @OR13 and @mgh128 who work with EPCIS data):
```yaml
"@context": 
  epcis: https://ns.gs1.org/epcis/
issued: 2022-09-01
stringThatOnlyLooksLikeADate: !string 2022-09-01
homepage: https://example.org/foo
stringThatOnlyLooksLikeAUrl: !string https://example.org/foo
urlThatMayBeMisspelled: !anyURI hxxp:\\i-cannot spell,con/my home page
epcis:readPoint: urn:epc:id:sgln:952005385.011.ts4711
epcis:epcList: https://id.gs1.org/01/70614141123451/21/2018
```

Note: the benefit of datatype `xsd:anyURI` (tag `!anyURI`) is that:
- the URL may be misspelled, because it is stored as a literal and semantic repos (at least rdf4j) don't check its syntax. How's that a benefit? Try to import a million CrunchBase "homepage" props and you'll see
- OWL ontologies frown upon ObjectProperties that don't lead to any triples (eg rdf:type owl:NamedIndividual and some others)

We could also use explicit delimiters eg `<...>` around URNs (URIs, IRIs), which will also enable the use of [CURIEs](https://www.w3.org/TR/curie/).
Eg below each of the props `epcis:readPoint, epcis:epcList` has 2 identical values (first a full URN, then a CURIE), 
without having to declare that these are `@id` properties:
```yaml
"@context": 
  epcis: https://ns.gs1.org/epcis/
  gtin: https://id.gs1.org/01/
  sgln: "urn:epc:id:sgln:"
epcis:readPoint: 
  - <urn:epc:id:sgln:952005385.011.ts4711>
  - <sgln:952005385.011.ts4711>
epcis:epcList:
  - <https://id.gs1.org/01/70614141123451/21/2018>
  - <gtin:70614141123451/21/2018>
```

The CURIE spec says
> rules for disambiguation in situations where the same string could be interpreted as either a CURIE or an IRI. 

I've seen this once in practice:
- `geo:lat` (prefix for eg the WGS ontology), vs
- `<geo:1.23,4.56>` (point using the `geo:` URI scheme, so the above prefix if used in a context precludes you from using this scheme)

> One way to do this is to require that all CURIEs be expressed as Safe_CURIEs, implying that all unbracketed strings are to be interpreted directly as IRIs.

Safe_CURIEs use `[...]` delimiters, so we could rewrite the above example as follows:
```yaml
"@context": 
  epcis: https://ns.gs1.org/epcis/
  gtin: https://id.gs1.org/01/
  sgln: "urn:epc:id:sgln:"
epcis:readPoint: 
  - urn:epc:id:sgln:952005385.011.ts4711
  - [sgln:952005385.011.ts4711]
epcis:epcList:
  - https://id.gs1.org/01/70614141123451/21/2018
  - [gtin:70614141123451/21/2018]
```
Here we avoid the need for any delimiters in URNs, but the brackets can be confused for "array in flow style":
```yaml
epcis:epcList: [ https://id.gs1.org/01/70614141123451/21/2018, [gtin:70614141123451/21/2018] ]
```
We'd need extra spaces around the array brackets, and some damn specialized YAML parsers to grok this.

@ioggstream @gkellogg @anatoly-scherbakov 
- Do you think this is useful, or on the contrary, it is dangerous?
- Should we define an "extended RDF schema" with such regexes, or stay clear of it?
- Which variants for expressing URI/CURIE do you like?

**Comment by VladimirAlexiev** [comment]
When a property is `@id`, its value must be resolved to URN/IRI regardless of any regexes.
I should be able to write:
```yaml
"@context":
  "@sigil": $
  $base: https://friends.com/
  knows: {$type: $id}
$id: valexiev
name: Vladimir
knows: 
  $id: gkellogg
  name: Gregg
```

Because writing `$id: !id valexiev` would be "unbearable".
